---
title: "Homework 6!"
author: "Wuraola Olawole"
date: "12/6/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(patchwork)
library(modelr)
library(mgcv)
```

```{r}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


### Problem 1

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1)
  ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa, AL") %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```


Start with one city.

```{r}
baltimore_df =
  homicide_df %>% 
  filter(city_state == "Baltimore, MD")
glm(resolution ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```


Try this across cities.

```{r}
models_results_df = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI")) 
```

```{r}
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```



## Problem 2

Find some residuals

```{r}
baby_df = 
  read_csv("./data/birthweight.csv") %>%
  janitor::clean_names() %>%
  mutate(
    babysex = as_factor(babysex),
    frace = as_factor(frace),
    mrace = as_factor(mrace),
    malform = as_factor(malform)
  ) %>%
  drop_na()
```

```{r}
baby_df %>% 
  ggplot(aes(x = bwt)) + geom_density()
```

```{r}
p1 = ggplot(baby_df, aes(blength, bwt)) + geom_point()
p2 = ggplot(baby_df, aes(bhead,bwt)) + geom_point()
p3 = ggplot(baby_df, aes(gaweeks, bwt)) + geom_point()
p4 = ggplot(baby_df, aes(smoken, bwt)) + geom_point()
p5 = ggplot(baby_df, aes(wtgain, bwt)) + geom_point()
p6 = ggplot(baby_df, aes(momage,bwt)) + geom_point()

(p1 + p2 + p3) / (p4 + p5 + p6)


```

One using length at birth and gestational age as predictors (main effects only)
One using head circumference, length, sex, and all interactions (including the three-way interaction) between these

```{r}

mod1 = 
      lm(bwt ~ blength + bhead + gaweeks + smoken + wtgain + momage , data = baby_df )
summary(mod1)
broom::tidy(mod1)
broom::glance(mod1)

```


```{r}
baby_res =
baby_df %>%
  add_residuals(mod1) %>%
  add_predictions(mod1) %>%
  select(bwt, blength, bhead , gaweeks , smoken , wtgain , momage, resid, pred)
  
   ggplot(baby_res, aes(x = pred, y = resid)) + geom_point() +
  geom_line(aes(y = pred), col = 'red') + 
  labs(title = "Residuals vs Fitted values plot",
       x = "Fitted values",
       y = "Residuals")
```



```{r}
mod2 =
      lm(bwt~ blength + gaweeks, data = baby_df)
  
mod3 =
      lm(bwt~ bhead + blength + babysex + bhead*blength + bhead*babysex + babysex*blength + babysex*blength*bhead, data = baby_df)

```


```{r}
cv_df = 
  crossv_mc(baby_df, 200) %>%
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

Fit candidate models
```{r}
mod_com_df = 
  cv_df %>% 
  mutate(
    mod_1  = map(train, ~lm(bwt ~ blength + bhead + gaweeks + smoken + wtgain + momage, data = .x)),
    mod_2  = map(train, ~lm(bwt~ blength + gaweeks, data = .x)),
    mod_3  = map(train, ~lm(bwt~ bhead + blength + babysex + bhead*blength + 
                      bhead*babysex + babysex*blength + babysex*blength*bhead, data = .x))) %>% 
  mutate(
    rmse_mod1 = map2_dbl(mod_1, test, ~rmse(model = .x, data = .y)),
    rmse_mod2 = map2_dbl(mod_2, test, ~rmse(model = .x, data = .y)),
    rmse_mod3 = map2_dbl(mod_3, test, ~rmse(model = .x, data = .y)))
```


```{r}
mod_com_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

```


## problem 3

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

exploratory
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point() 
```


```{r}
bootstr =
  weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)),
    r_hat = map(models, broom::glance),
    results = map(models, broom::tidy)) %>% 
  select(results, r_hat) %>% 
  unnest(results, r_hat) %>%
mutate(term = str_replace(term,"\\(Intercept\\)","Intercept"))
  
```

```{r}
est =
bootstr %>%
select(term, estimate, adj.r.squared) %>%
pivot_wider(
names_from = "term",
values_from = "estimate"
) %>%
  janitor::clean_names() %>%
  rename(rhat_sq = adj_r_squared) %>%
  mutate(
    log_est = log(intercept * tmin)
  ) %>%
  select(-intercept, -tmin)

```


```{r}

est %>%
  pivot_longer(1:2,
               names_to = "estimates",
               values_to = "values") %>%
  ggplot(aes(x = estimates, y = values, fill = estimates)) + geom_violin(alpha = 0.4) 
           

```

```{r}
est %>%
  pivot_longer(1:2,
               names_to = "estimates",
               values_to = "values") %>% 
  group_by(estimates) %>% 
  summarize(
    ci_lower = quantile(values, 0.025), 
    ci_upper = quantile(values, 0.975))
```

